config/routes.rb
ZombieBlog::Application.routes.draw do

  devise_for :authors

  
  resources :entries do
    resources :comments, only: [:create] do
      member do
        put 'inappropiate'
      end
    end
  end
  resources :authors
  resources :entries
  resources :users
  resources :tags

  root :to => 'entries#index'
  

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  attr_accessible :bio, :name, :photo

  validates_presence_of :name, :email
  validates_uniqueness_of :name, :email
  validates_email_format_of :email 

  has_many :entries
  has_many :comments, :as => :commenter

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :publish_date, :approved, :name, :email, :commenter

  validates_presence_of :content, :publish_date, :entry_id
  validates_length_of :content, minimum: 10

  belongs_to :entry
  belongs_to :commenter, :polymorphic => true

  scope :approving, where(approved: true)
  scope :by_date, order("publish_date DESC")

  attr_accessor :name, :email

  before_validation :set_commenter, :unless => :commenter
  before_validation :set_date

  def mark_as_spam
    self.update_attribute(:approved, false)
  end

  private

  def set_commenter
    commenter_instance = Author.where(email: email).first
    if commenter_instance.nil?
       commenter_instance = User.where(:email => email).first
    end
    if commenter_instance.nil?
      commenter_instance = User.new(name: name, email: email)
      commenter_instance.save
    end
    self.commenter = commenter_instance
  end

  def set_date
    self.publish_date = DateTime.now
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  attr_accessible :content, :publish_date, :title
  
  validates_presence_of :content, :publish_date, :title, :author_id
  validates_length_of :content, minimum: 10

  has_and_belongs_to_many :tags
  has_many :comments, dependent: :destroy

  belongs_to :author

  scope :published, where("publish_date <= ? ", DateTime.now)
  scope :by_date, order("publish_date DESC")


  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  validates_uniqueness_of :name

  has_and_belongs_to_many :entries

  def article_count
  	entries.size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :commenter

  validates_presence_of :name, :email
  validates_uniqueness_of :name, :email
  validates_email_format_of :email 

  has_many :comments, :as => :commenter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	protect_from_forgery
	before_filter :tag_cloud, :login
	before_filter :set_locale
	
	# app/controllers/application_controller.rb
	def default_url_options(options={})
	  logger.debug "default_url_options is passed options: #{options.inspect}\n"
	  { locale: I18n.locale }
	end						

	def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
	end

	protected
	def tag_cloud
	@tags = Tag.all.sort_by{|e| e.article_count}.reverse!
	end

	def login
	@c_author = current_author
	end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def show
    @author = Author.find(params[:id])
    @entries = @author.entries.published.by_date.all
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @entry = Entry.find(params[:entry_id])
    @comment = @entry.comments.new(params[:comment])
    
    unless @c_author.nil?
      @comment.email = @c_author.email
      @comment.name = @c_author.name
    end

    if @comment.save
      redirect_to @entry, notice: 'Comment succesfully published'
    else
      redirect_to @entry, notice: "Error: comment couldn't be published"
    end
  end

  def inappropiate
    @entry = Entry.find(params[:entry_id])
    @comment = Comment.find(params[:id])
    @comment.mark_as_spam
    redirect_to  @entry, notice: 'Comment marked as inappropiate'
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_author!, except: [ :index, :show]
  before_filter :get_entry, only: [ :edit, :update, :show]
  before_filter :authorize, only: [ :edit, :update]

  def index
    @entries = Entry.published.by_date.all	
  end

  def show
    @comments =  @entry.comments.approving.by_date.all
  end

  def new
    @entry = Entry.new  
  end

  def edit
  end

  def create

    @entry = current_author.entries.new(params[:entry])

    if @entry.save
      redirect_to @entry, notice: 'Entry succesfully published'
    else
      redirect_to @entry, notice: "Error: entry couldn't be published"
    end
  end

  def update

    if @entry.update_attributes(params[:entry])
      redirect_to @entry, notice: 'Entry succesfully updated'
    else
      render action: "edit", notice: "Error: entry couldn't be updated"
    end

  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to @c_author, notice: 'Entry deleted'
  end

  private
  def authorize
    if @entry.author != current_author
      redirect_to @entry, notice: 'You are not allowed to edit other author entries'
    end
  end

  def get_entry
    @entry = Entry.find(params[:id])
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

def show
    @tag = Tag.find(params[:id])
    @entries = @tag.entries.published.by_date.all
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
    @user = User.find(params[:id])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_tag(tag)
  	tag << ','
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_current_author.html.haml
-if @c_author.nil?
	%h3= t('.guest')

	%ul.sidemenu
		%li
			= link_to t('.sign_up'), new_author_registration_path
			|
			\#{link_to t('.log_in'), new_author_session_path}

-else
	%h3=link_to @c_author.name, @c_author

	%ul.sidemenu
		%p
			%img.float-left{src:"../app/assets/images/firefox-gray.jpg", width:"40", height:"40", alt:"firefox"}/
			%h4= t('.zombiography')
			%p= @c_author.bio

			%p.postmeta
				= pluralize(@c_author.comments.size, t('.comment'))
				|
				\#{pluralize(@c_author.entries.published.size, t('.entry'))}
			%li
				= link_to t('.publish_entry'), new_entry_path
				|
				\#{link_to t('.log_out'), destroy_author_session_path}

app/views/authors/show.html.haml
%h2=@author.name

%p
	%img.float-left{src:"../app/assets/images/firefox-gray.jpg", width:"100", height:"120", alt:"firefox"}/
	%h4= t('.zombiography')
	%p= @author.bio
	%h4
		= t('.mail') 
		= @author.email

%p.postmeta
	= pluralize(@author.comments.size, t('.comment'))
	|
	\#{pluralize(@author.entries.published.size, t('.entry'))}

%h2= t('.published')
- @entries.each do |entry|
	%blockquote
		%h4= link_to entry.title, entry
		%p.align-right= entry.publish_date.to_formatted_s(:long_ordinal)

app/views/entries/_comment_box.html.haml
#commentbar
	%ul.commentmenu
		- @comments.each do |comment|
			%li
				= t('.written')
				= link_to comment.commenter.name, comment.commenter
				= t('.on')
				= comment.publish_date.to_formatted_s(:long_ordinal)
				-if comment.entry.author ==  @c_author
					= link_to t('.flag_un'), inappropiate_entry_comment_path(@entry, comment), :method => :put
				%br/
				%span= comment.content

	= simple_form_for [@entry , Comment.new], :html=> { id: 'contactform' } do |f|
		
		- if @c_author.nil?
			%p= t('.post')
			%label{for: "name"} #{t('.name')}
			= f.input :name, label: false, required: true, input_html: {id: 'name'}
			%label{for: "email"} #{t('.mail')}
			= f.input :email, label: false, required: true, input_html: {id: 'email'}

		- else
			%p
				= t('.post')
				,
				= link_to @c_author.name, @c_author

		%label{for: "content"} #{t('.comment')}
		= f.input :content, label: false, input_html: {id: 'content'}
		= f.button :submit 

app/views/entries/_form.html.haml
= simple_form_for @entry, :html=> { id: 'contactform' } do |f|
	.form-group
		= f.label t('.title')
		%br
		= f.input :title, label: false, required: true, input_html: {id: 'title'}
	.form-group
		= f.label t('.publish_date')
		%br
		= f.date_select :publish_date, required: true, input_html: {id: 'date'} 
		= f.time_select :publish_date, required: true, input_html: {id: 'date'} 
	.form-group
		= f.label t('.content')
		%br
		= f.input :content, label: false, input_html: {id: 'content'}
	= f.button :submit

app/views/entries/edit.html.haml
%h2= t('.edit entry')
= render 'form'

app/views/entries/index.html.haml
- @entries.each do |entry|
	%h2= link_to entry.title, entry

	%p.post-info 
		= t('.written')
		= link_to entry.author.name, entry.author
		| 
		= t('.tags')
		- entry.tags.each do |tag|
			=link_to format_tag(tag.name), tag
			
	%p= entry.content

	%p.postmeta
		=link_to t('.read_more'), entry
		|
		\#{pluralize(entry.comments.size , t('.comment'))}
		|
		%span.date= entry.publish_date.to_formatted_s(:long_ordinal)
		-if entry.author == @c_author
			|
			#{link_to t('.edit_entry'), edit_entry_path(entry) } 
			|
			#{link_to t('.delete_entry'), entry, :method => :delete}  

app/views/entries/new.html.haml
%h2= t('.new_entry')
= render 'form'

app/views/entries/show.html.haml
%h2= @entry.title

%p.post-info 
	= t('.written')
	= link_to @entry.author.name, @entry.author
	| 
	= t('.tags')
	- @entry.tags.each do |tag|
		=link_to format_tag(tag.name), tag

%p= @entry.content

%p.postmeta
	=pluralize(@entry.comments.size , t('.comment'))
	|
	%span.date= @entry.publish_date.to_formatted_s(:long_ordinal)
	-if @entry.author == @c_author
		|
		#{link_to t('.edit_entry'), edit_entry_path(@entry) }
		|
		#{link_to t('.delete_entry'), @entry, :method => :delete}  

= render partial: 'comment_box'				

app/views/layouts/_lang.html.haml
%h3= t('.select')

%ul.sidemenu
	%li
		- if I18n.locale == I18n.default_locale
			= link_to "Español", :locale=>'es'
		- else
			= link_to "English", :locale=>'en'

app/views/layouts/_tags_cloud.html.haml
%h3= t('.tag_cloud')

%ul.sidemenu
	%li
		- @tags.each do |tag|
			= link_to format_tag(tag.name), tag

app/views/layouts/application.html.haml
!!!
/[if IE 7 ] <html class="ie7 oldie">
/[if IE 8 ] <html class="ie8 oldie">
/[if IE 9 ] <html class="ie9">
/ [if (gt IE 9)|!(IE)]><!
%html
	/ <![endif]
	
	%head
		%meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
		%meta{charset: "utf-8"}/
		%meta{content: "", name: "description"}/
		%meta{content: "", name: "author"}/
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
		%title= t('.zombie_blog', :default => 'Zombie Blog')
		/[if lt IE 9]
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	
	%body
		/ wrap starts here
		#wrap
			/ header
			#header
				%h1#logo-text= link_to t('.zombie_blog', :default => 'Zombie Blog'), root_path
				%p#intro= t('.description')
			/ header ends
			
			/ content-wrap starts
			#content-wrap
				#main
					- flash.each do | name, msg|
						= content_tag :div, msg, id: "flash_#{name}"
					= yield
				/ main ends
				/ sidebar starts
				#sidebar
					= render partial: "authors/current_author"
					= render partial: "layouts/lang"
					= render partial: 'layouts/tags_cloud'
				/ sidebar ends
			/ content-wrap ends

			/ footer starts here
			#footer
				#footer-left
					%p
						\
						= t('.zombieright', :default => '© Zombieright info here')	 
						= t('.creator', :default => 'Created by Javier Pradillo')
				#footer-right
					%p.align-right
						%a{href: "index.html"} Home
						|
						%a{href: "index.html"} Sitemap
						|
						%a.rssfeed{href: "index.html"} RSS Feed
			/ footer ends here
		/ wrap ends here

app/views/tags/show.html.haml
%h2= @tag.name
	
%p.postmeta
	= pluralize(@entries.size, t('.entry'))

%h2=t('.related')

- @entries.each do |entry|
	%blockquote
		%h4= link_to entry.title, entry	
		%p.align-right= entry.publish_date.to_formatted_s(:long_ordinal)

app/views/users/show.html.haml
%h2= @user.name

%p
	%h4
		= t('.mail') 
		= @user.email

%p.postmeta
	= pluralize(@user.comments.size, t('.comment'))